version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_js
    image: node:10.15.3-alpine
    ports:
      - 3000:3000
    environment:
      - NODE_PORT=3000
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: npm start
    depends_on:
      - postgres

  postgres:
    container_name: pg_database
    image: "kartoza/postgis"
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=Test
    ports:
      - "5432:5432"

  pgAdmin:
    container_name: pg_admin
    image: "dpage/pgadmin4"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@user.com
      - PGADMIN_DEFAULT_PASSWORD=user
    ports:
      - "80:80"

networks:
  postgres:
    driver: bridge

volumes:
  postgis-data:
  pgadmin:
  node_modules:
